site_name: "lm-datasets: Documentation"
site_url: https://github.com/malteos/lm-datasets/

site_description: "Documentation of the lm-datasets framework."
site_author: "Malte Ostendorff and lm-datasets contributors"
docs_dir: docs/
repo_name: "GitHub"
repo_url: "https://github.com/malteos/lm-datasets/"

nav:
  - Home: index.md
  - "Getting started": getting-started.md
  - "Framework overview": overview.md
  - "Config files": config-files.md
  - "Extract text data": extract-text-data.md
  - "Adding your own data": add-your-own-data.md
  - "Compose training and validation dataset": compose-train-validation-data.md

  - "Related work": related-work.md
  - "API reference":
    - "BaseDataset": api/base_dataset.md
    - "HFDataset": api/hf_dataset.md
    - "JSONLDataset": api/jsonl_dataset.md
    - "Config": api/config.md


theme:
  name: "material"
  # logo: "images/apple-touch-icon.png"

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
  - search
  - exclude:
      glob:
        - README.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences