# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.13"

    - name: Install TLSH
      run: |
        echo Installing TLSH dependency ....
        make install-tlsh

    - name: Install package and dependencies
      run: |
        echo Installing dependencies ....
        make install

    - name: Lint with ruff
      run: |
        echo "Checking synatix and format errors in files ..."
        make lint

    - name: Test with pytest
      run: |
        make test